# 线上配置文件
server:
  port: 8101
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.22.65:3306/oj?serverTimezone=Asia/Shanghai
    username: user
    password: chenshijie123
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 生产环境关闭日志
# 接口文档的配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.csj.ojbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true

SandBox:
  type: remote